# Generated by Django 6.0 on 2025-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom / Pseudo')),
                ('metier', models.CharField(max_length=150, verbose_name='Métier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Image de profil')),
                ('icon', models.CharField(default='fa-laptop-code', max_length=50, verbose_name='Icône FontAwesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accueil - Profil',
                'verbose_name_plural': 'Accueil - Profils',
            },
        ),
    ]
