# Generated by Django 6.0 on 2025-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, help_text="Liste d'URL ou chemins des images du projet", null=True)),
                ('code_url', models.URLField(blank=True, help_text='Lien vers le code source', null=True)),
                ('demo_url', models.URLField(blank=True, help_text='Lien vers la démo en ligne', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
