# Generated by Django 6.0 on 2025-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='projets/', verbose_name='Image du projet'),
        ),
    ]
