# Generated by Django 6.0 on 2025-12-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(help_text="Classe FontAwesome de l'icône (ex: fab fa-python)", max_length=50)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre de la compétence')),
                ('description', models.CharField(max_length=255, verbose_name='Description courte')),
                ('niveau', models.PositiveIntegerField(help_text='Valeur entre 0 et 100 pour la barre de progression', verbose_name='Niveau (%)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le template")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre'],
            },
        ),
    ]
