# Generated by Django 6.0 on 2025-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(help_text='Pourcentage (0-100)')),
                ('color_class', models.CharField(default='bg-primary', help_text='Classe bootstrap pour la couleur de la barre de progression', max_length=20)),
            ],
        ),
    ]
