# Generated by Django 6.0 on 2025-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Poste / Titre')),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True, verbose_name='Entreprise')),
                ('date_debut', models.CharField(max_length=50, verbose_name='Date de début')),
                ('date_fin', models.CharField(max_length=50, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-created_at'],
            },
        ),
    ]
