# Generated by Django 6.0 on 2025-12-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('parcours', 'Parcours'), ('experience', 'Expérience professionnelle')], default='experience', max_length=20),
        ),
    ]
