# Generated by Django 6.0 on 2025-12-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('avancé', 'Avancé'), ('expert', 'Expert')], default='intermédiaire', help_text='Niveau de compétence', max_length=20),
        ),
    ]
