# Generated by Django 6.0 on 2025-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du parcours')),
                ('annee_debut', models.PositiveIntegerField(verbose_name='Année de début')),
                ('annee_fin', models.PositiveIntegerField(verbose_name='Année de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage sur le site")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['ordre', '-annee_debut'],
            },
        ),
    ]
